config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'articles#index'

  get 'signup', to: 'users#new'

  resources :articles
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
  validates :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles
  before_save { self.email = email.downcase }
  validates :username, presence: true,
            uniqueness: { case_sensitive: false },
            length: { minimum: 3, maximum: 25 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email, presence: true, length: { maximum: 105 },
            uniqueness: { case_sensitive: false },
            format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    # return current_user if already exist else find user in
    # database set in the session
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    # check if current user is logged-in
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:danger] = "Please login to access this page"
      redirect_to root_path
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:edit, :update, :show, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  
  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def edit

  end

  def create
  @article = Article.new(article_params)
  @article.user = current_user
    if @article.save
      flash[:notice] = "Article successfully created!"
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end

  def update
    if @article.update(article_params)
      flash[:notice] = "Article successfully updated!"
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end

  def show
    if @article = Article.find_by_id(set_article).present?
      set_article
    else
      content_not_found
    end
  end

  def destroy
    @article.destroy
    flash[:notice] = "Article successfully deleted!"
    redirect_to articles_path
  end

  private
  def article_params
    params.require(:article).permit(:title, :description)
  end

  def set_article
    @article = Article.find(params[:id])
  end

  def require_same_user
    if current_user != @article.user
      flash[:danger] = "You can only edit or delete your own articles"
      redirect_to root_path
    end
  end

  def content_not_found
    render file: "#{Rails.root}/public/404", layout: true, status: :not_found
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to user_path(current_user) if logged_in?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "Welcome back #{user.username}"
      redirect_to user_path(user)
    else
      flash.now[:danger] = "There was something wrong with your login information"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "You have logged out"
    redirect_to articles_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :show]
  before_action :require_same_user, only: [:show, :edit, :update]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Account successfully created!"
      # redirect_to user_path(@user)
      redirect_to articles_path
    else
      render 'new'
    end
  end

  def edit

  end

  def update
    if @user.update(user_params)
      flash[:success] = "Your Accout was updated successfully!"
      redirect_to articles_path
    else
      render 'edit'
    end
  end

  def show

  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user
      flash[:danger] = "You can only access your own account"
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_article.html.erb
<div id="articles" class="row">
  <% obj.each do |article| %>
    <div class="article-container col-md-12">
      <h3 class="article-title"> <%= article.title %></h3>
      <small class=article-details>
        <div class="article-author">
          <strong>Author:</strong> <%=  article.user.username if article.user%>
        </div>
        <div class="article-created">
          <strong>Published:</strong> <%= time_ago_in_words(article.created_at) %> ago,
        </div>
        <div class ="article-update">
          <strong>last updated:</strong> <%=  time_ago_in_words(article.updated_at) %> ago
        </div>
      </small>

      <p class="article-description"> <%= article.description %></p>

      <% if logged_in? && current_user == article.user %>
      <div id="actions">
        <%= link_to "Edit Article", edit_article_path(article), class: "edit-article" %>
        <%= link_to "Delete Article", article_path(article), class: "delete-article", method: :delete %>
      </div>
      <% end %>
      </div>
    <% end %>
    </div>

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
<div class="error-message-container">
  <h3> Failed creating article! </h3>
  <ul>
    <% @article.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<div class="article-form-container">
<%= form_for @article do |f| %>
<table class="article-table">
  <tr>
    <td><%= f.label :title %></td>
    <td><%= f.text_field :title, id: "title" %></td>
  </tr>
  <tr>
    <td><%= f.label :description %></td>
    <td><%= f.text_area :description, id: "description" %></td>
  </tr>
  </table>
<p>
<%= f.submit "Save", id: "save"%>
</p>
<% end %>

<p><%= link_to "Back to My Articles", user_path(current_user), id: "back" %></p>
</div>

app/views/articles/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div id="page-title">
        <h3> Edit Article </h3>
      </div>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/articles/index.html.erb
<div class="container">
  <div class="row">
      <div class="col-md-12">
        <div id="page-title">
          <h2> All Articles Listing </h2>
        </div>
          <%= render 'article', obj: @articles %>
      </div>
  </div>
</div>

app/views/articles/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div id="page-title">
        <h3> New Article </h3>
      </div>
      <%= render 'form' %>

app/views/articles/show.html.erb
<div class="container">
  <div class="row">
    <div class="article-container col-md-12">
      <h2 class="article-title"><%= @article.title %></h2>
      <p class="article-description">Description: <%= @article.description %></p>

      <p><%= link_to "Back to My Articles", user_path(current_user), id: "back" %></p>
    </div>
  </div>
</div>

app/views/layouts/_messages.html.erb
<div class="container">
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <% flash.each do |name, msg| %>
      <div id="msg" class='alert alert-<%="#{name}" %>'>
        <a href="#" class="close" data-dismiss="alert">
          &#215;
        </a>
        <%= msg %>
      </div>
    <% end %>
  </div>
</div>
</div>

app/views/layouts/_navigations.html.erb
<div class="container">
  <div class="row">
    <header id="top">
      <div  class="col-md-12">
        <div id="logo">
          <%= link_to "My Blogsite", root_path %>
        </div>
      </div>

      <div  class="col-md-12">
        <div id="nav">
          <ul id="navlinks">
            <li><%= link_to "All Articles", articles_path, id: "all-articles"%> </li>

            <% if logged_in? %>
            <li><%= link_to "My Articles", user_path(current_user), id: "my-articles" %> </li>
            <li><%= link_to 'Log out', logout_path, method: :delete, id: "logout" %></li>
            <% else %>
            <li><%= link_to 'Login', login_path, id: "login" %></li>
            <li><%= link_to "Register", signup_path, id: "register" %> </li>
            <% end %>
          </ul>
        </div>
      </div>
    </header>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My Blogsite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigations' %>
    <%= render 'layouts/messages' %>
    <%= yield %>
    <br />
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
<div class="error-message-container">
  <h3> Failed creating user! </h3>
  <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div class="article-form-container">
<%= form_for @user do |f| %>
<table class="article-table">
  <tr>
    <td><%= f.label :username, "Name" %></td>
    <td><%= f.text_field :username, id: "username" %></td>
  </tr>
  <tr>
    <td><%= f.label :email %></td>
    <td><%= f.text_field :email, id: "email" %></td>
  </tr>
  <tr>
    <td><%= f.label :password %></td>
    <td><%= f.password_field :password, id: "password" %></td>
  </tr>
  </table>
<p>
<%= f.submit(@user.new_record? ? "Sign-up" : "Save") %>
</p>

<% end %>

<p><%= link_to "Back to Articles", articles_path, id: "back" %></p>
</div>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">

      <div id="page-title">
        <h3>Edit Account </h3>
      </div>

      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
<div class="row">
    <div class="col-md-12">
      <div id="page-title">
        <h2> All Users </h2>
      </div>

      <% @users.each do |user| %>
      <div class="users">
        <div class=""><%= link_to user.username, user_path(user) %></div>
        <div class="article-count"><%= pluralize(user.articles.count, "article") if user.articles %></div>
      <% end %>
    </div>
</div>
</div>

app/views/users/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">

      <div id="page-title">
        <h3>Signup Account </h3>
      </div>

      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
      <div class="col-md-12">
        <div id="page-title">
          <h2> All Articles Listing </h2>
        </div>

        <div id="create-article">
          <%= link_to "Create New Article", new_article_path, id: "create-article" %>
        </div>
        <br />
        <%= render 'articles/article', obj: @user.articles %>
      </div>
  </div>
</div>